name: CI for Wordpress 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        services: 
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
                    MYSQL_USER: ${{ secrets.MYSQL_USER }}
                    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"  
                    --health-interval=10s
                    --health-timeout=10s
                    --health-retries=10

        steps:
            - uses: actions/checkout@v2
            - name: Run the Docker image
              run: docker-compose up -d

            - name: Run the tests
              run: |
                # Add commands to test your application
                echo "Testing the application"
            
            # Set up continuous deployment (CD)
            - name: Push Docker images
              run: |
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                docker-compose push hungmanhhoang/wordpress:latest

            - name: Deploy to production
              run: |
                    # Add commands to deploy your application
                    echo "Deploying the application"
              